sudo: false
language: android
dist: trusty
cache:
  directories:
   - node_modules
 
android:
  components:
    - build-tools-29.0.2
    - android-29
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    
env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    
before_install:
    - chmod +x gradlew
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo "$LICENSES_HASH" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo "$LICENSES_HASH_TWO" >> "$ANDROID_HOME/licenses/android-sdk-license"
    - echo y | sdkmanager tools
    - echo y | sdkmanager "system-images;android-29;default;x86_64"
    - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install bridge-utils libpulse0 libvirt-bin qemu-kvm virtinst ubuntu-vm-builder
    - echo no | avdmanager create avd --force -n emu -k "system-images;android-29;default;x86_64"
    - $ANDROID_HOME/emulator/emulator -avd emu -no-audio -no-window -no-boot-anim &
    
before_script:
    - android-wait-for-emulator
    - adb shell settings put global window_animation_scale 0 &
    - adb shell settings put global transition_animation_scale 0 &
    - adb shell settings put global animator_duration_scale 0 &
    - adb shell input keyevent 82 &
    
script:
    - android list target
    - ./gradlew connectedAndroidTest
    - ./gradlew check connectedCheck --stacktrace